-- 002: obl_payment_orders
CREATE TABLE IF NOT EXISTS obl_payment_orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(32) UNIQUE NOT NULL,
    biz_order_no VARCHAR(64) NOT NULL,
    base_amount DECIMAL(10, 2) NOT NULL,
    actual_amount DECIMAL(10, 4) NOT NULL,
    amount_in_sun VARCHAR(20) NOT NULL,
    wallet_address VARCHAR(42) NOT NULL,
    wallet_id BIGINT NOT NULL,
    status ENUM('pending', 'paid', 'confirmed', 'completed', 'expired', 'failed', 'cancelled') DEFAULT 'pending',
    tx_hash VARCHAR(64) NULL,
    block_number BIGINT NULL,
    confirmations INT DEFAULT 0,
    required_confirmations INT DEFAULT 6,
    expires_at DATETIME NOT NULL,
    paid_at DATETIME NULL,
    confirmed_at DATETIME NULL,
    completed_at DATETIME NULL,
    error_message TEXT NULL,
    metadata JSON NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (wallet_id) REFERENCES obl_payment_wallets(id),
    INDEX idx_order_no (order_no),
    INDEX idx_biz_order_no (biz_order_no),
    INDEX idx_status (status),
    INDEX idx_wallet_amount (wallet_address, actual_amount),
    INDEX idx_tx_hash (tx_hash),
    INDEX idx_expires_at (expires_at),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
